import { StyleSheet } from "react-native";

// SuggestedLessonsScreen komponentining barcha stillarini saqlovchi stil obyekti
export const lessonStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FA",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#3C5BFF",
    paddingTop: 50,
    paddingBottom: 16,
    paddingHorizontal: 20,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  backButton: {
    width: 40,
    height: 40,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  headerTitleContainer: {
    flexDirection: "column",
  },
  levelTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 2,
  },
  dateText: {
    fontSize: 12,
    color: "rgba(255, 255, 255, 0.7)",
  },
  coinsContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  coinsText: {
    color: "#FFFFFF",
    marginLeft: 6,
    fontWeight: "bold",
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  lessonCardsContainer: {
    flexDirection: "column",
    gap: 16,
  },
  lessonCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    position: "relative",
  },
  disabledCard: {
    opacity: 0.6,
  },
  lessonCardContent: {
    flexDirection: "column",
  },
  lessonTitleContainer: {
    flex: 1,
  },
  lessonTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 4,
  },
  lessonProgress: {
    fontSize: 14,
    color: "#666",
  },
  // Legacy styles from original design
  lessonCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  progressBadge: {
    backgroundColor: "#E3F2FD",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  progressText: {
    color: "#2196F3",
    fontSize: 12,
    fontWeight: "bold",
  },
  lessonCardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  wordsCount: {
    color: "#757575",
    fontSize: 12,
  },
  // Original design elements
  lockedBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "#9E9E9E",
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  completedBadge: {
    backgroundColor: "#4CAF50",
    borderRadius: 15,
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 16,
    right: 16,
  },
  completedText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "bold",
  },
  lessonCoinsBadge: {
    position: "absolute",
    bottom: 10,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF9C4",
    borderRadius: 15,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  lessonCoinsText: {
    color: "#FFA000",
    fontWeight: "bold",
    marginLeft: 4,
  },
  // Other styles
  progressBarBg: {
    height: 6,
    backgroundColor: "#EEEEEE",
    borderRadius: 3,
    marginBottom: 12,
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#4CAF50",
    borderRadius: 3,
  },
  lockedIcon: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -15 }, { translateY: -15 }],
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  gameContainer: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  gameHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#3C5BFF",
    paddingTop: 50,
    paddingBottom: 16,
    paddingHorizontal: 20,
    position: "relative",
  },
  closeButton: {
    position: "absolute",
    left: 20,
    top: 50,
    width: 32,
    height: 32,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  gameTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
  },
  // Dars bosqichlari uchun stil
  lessonDetailsHeader: {
    marginBottom: 20,
  },
  backToLessonsButton: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  backToLessonsText: {
    color: "#666",
    fontSize: 14,
    marginLeft: 8,
  },
  selectedLessonTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 16,
  },
  stepsContainer: {
    flexDirection: "column",
    gap: 12,
  },
  stepCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  completedStepCard: {
    borderLeftWidth: 4,
    borderLeftColor: "#4CAF50",
  },
  lockedStepCard: {
    opacity: 0.6,
  },
  stepHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  stepTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  completedStepTitle: {
    color: "#4CAF50",
  },
  wordCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 20,
    marginVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    alignItems: "center",
  },
  englishWord: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#3C5BFF",
    marginBottom: 8,
  },
  uzbekWord: {
    fontSize: 16,
    color: "#666",
  },
  optionsContainer: {
    marginTop: 20,
    width: "100%",
    paddingHorizontal: 20,
  },
  optionButton: {
    backgroundColor: "#F5F7FA",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    width: "100%",
    alignItems: "center",
  },
  optionButtonSelected: {
    backgroundColor: "#E3F2FD",
    borderColor: "#2196F3",
    borderWidth: 1,
  },
  optionButtonCorrect: {
    backgroundColor: "#E8F5E9",
    borderColor: "#4CAF50",
    borderWidth: 1,
  },
  optionButtonIncorrect: {
    backgroundColor: "#FFEBEE",
    borderColor: "#F44336",
    borderWidth: 1,
  },
  optionText: {
    fontSize: 16,
    color: "#333",
  },
  progressContainer: {
    paddingHorizontal: 20,
    marginTop: 20,
  },
  progressCounter: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  progressCount: {
    fontSize: 14,
    color: "#666",
  },
  progressBar: {
    height: 8,
    backgroundColor: "#EEEEEE",
    borderRadius: 4,
    width: "100%",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#4CAF50",
    borderRadius: 4,
  },
  matchContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  matchColumn: {
    flex: 1,
  },
  matchColumnTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 12,
    textAlign: "center",
  },
  matchWordButton: {
    backgroundColor: "#F5F7FA",
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    alignItems: "center",
  },
  matchWordButtonSelected: {
    backgroundColor: "#E3F2FD",
    borderColor: "#2196F3",
    borderWidth: 1,
  },
  matchWordButtonMatched: {
    backgroundColor: "#E8F5E9",
    borderColor: "#4CAF50",
    borderWidth: 1,
    opacity: 0.7,
  },
  matchWordText: {
    fontSize: 14,
    color: "#333",
  },
  arrangeContainer: {
    flex: 1,
    padding: 20,
  },
  arrangeWordContainer: {
    alignItems: "center",
    marginBottom: 30,
  },
  arrangePrompt: {
    fontSize: 16,
    color: "#666",
    marginBottom: 10,
  },
  arrangeUzbekWord: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#3C5BFF",
  },
  letterTiles: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
    marginTop: 20,
  },
  letterTile: {
    backgroundColor: "#F5F7FA",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 40,
    alignItems: "center",
  },
  letterText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
  },
  writeContainer: {
    flex: 1,
    padding: 20,
  },
  writePrompt: {
    fontSize: 16,
    color: "#666",
    marginBottom: 10,
    textAlign: "center",
  },
  writeUzbekWord: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#3C5BFF",
    textAlign: "center",
    marginBottom: 30,
  },
  writeInput: {
    borderWidth: 1,
    borderColor: "#DDD",
    borderRadius: 12,
    padding: 16,
    fontSize: 18,
    color: "#333",
    textAlign: "center",
    marginBottom: 20,
  },
  submitButton: {
    backgroundColor: "#3C5BFF",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
  },
  submitButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    width: "100%",
    overflow: "hidden",
  },
  modalHeader: {
    backgroundColor: "#3C5BFF",
    padding: 16,
  },
  modalTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
  modalBody: {
    padding: 20,
  },
  modalMessage: {
    fontSize: 16,
    color: "#333",
    textAlign: "center",
    lineHeight: 22,
  },
  modalFooter: {
    padding: 16,
    paddingTop: 0,
  },
  modalButton: {
    backgroundColor: "#3C5BFF",
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
  },
  modalButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  mistakesContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 10,
  },
  mistakeIcon: {
    color: "#F44336",
    marginRight: 4,
  },
  wordsProgressContainer: {
    marginTop: 10,
    alignItems: "center",
  },
});

export default lessonStyles;
